/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPublicidadeRouteImport } from './routes/admin.publicidade'
import { Route as AdminMonitoresRouteImport } from './routes/admin.monitores'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicidadeRoute = AdminPublicidadeRouteImport.update({
  id: '/publicidade',
  path: '/publicidade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoresRoute = AdminMonitoresRouteImport.update({
  id: '/monitores',
  path: '/monitores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/monitores': typeof AdminMonitoresRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/monitores': typeof AdminMonitoresRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/monitores': typeof AdminMonitoresRoute
  '/admin/publicidade': typeof AdminPublicidadeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/conteudo'
    | '/admin/monitores'
    | '/admin/publicidade'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/conteudo'
    | '/admin/monitores'
    | '/admin/publicidade'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/conteudo'
    | '/admin/monitores'
    | '/admin/publicidade'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publicidade': {
      id: '/admin/publicidade'
      path: '/publicidade'
      fullPath: '/admin/publicidade'
      preLoaderRoute: typeof AdminPublicidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitores': {
      id: '/admin/monitores'
      path: '/monitores'
      fullPath: '/admin/monitores'
      preLoaderRoute: typeof AdminMonitoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminMonitoresRoute: typeof AdminMonitoresRoute
  AdminPublicidadeRoute: typeof AdminPublicidadeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConteudoRoute: AdminConteudoRoute,
  AdminMonitoresRoute: AdminMonitoresRoute,
  AdminPublicidadeRoute: AdminPublicidadeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
